############# Español navigation ##############

# main menu
[[main]]
name = "Inicio"
url = ""
weight = 1

[[main]]
name = "Nosotros"
url = "about/"
weight = 2

[[main]]
name = "Servicios"
url = "service/"
weight = 3
  
[[main]]
name = "Contacto"
url = "contact/"
weight = 4


# footer menu
[[footer]]
name = "Acerca"
url = "about/"
weight = 2

[[footer]]
name = "Servicios"
url = "service/"
weight = 3

[[footer]]
name = "Contacto"
url = "contact/"
weight = 4