############# German navigation ##############

# main menu
[[main]]
name = "Startseite"
url = ""
weight = 1

[[main]]
name = "Über uns"
url = "about/"
weight = 2

[[main]]
name = "Projekt"
url = "project/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
weight = 5
name = "More"
hasChildren = true

  [[main]]
  parent = "More"
  name = "Service"
  url = "service/"
  weight = 1

  [[main]]
  parent = "More"
  name = "Pricing"
  url = "pricing/"
  weight = 2

  [[main]]
  parent = "More"
  name = "Häufige Fragen"
  url = "faq/"
  weight = 3
  
[[main]]
name = "Kontakt"
url = "contact/"
weight = 6


# footer menu
[[footer]]
name = "Über uns"
url = "about/"
weight = 2

[[footer]]
name = "Projekt"
url = "project/"
weight = 3

[[footer]]
name = "Dienstleistung"
url = "service/"
weight = 4

[[footer]]
name = "Preise"
url = "pricing/"
weight = 5

[[footer]]
name = "Häufige Fragen"
url = "faq/"
weight = 6

[[footer]]
name = "Kontakt"
url = "contact/"
weight = 7